### ISSUE TITLE
IA milestone

### ISSUE THREAD

**Issue by quentin-sommer** [quentin-sommer/gomoku-back#2]
- [x] Add boolean field in ENTER_ROOM to know if it's a human vs AI or human vs human game 
- [x] Add new protocol AI_LEVEL with strengh as integer
- [x] Add new protocol SUGGESTED_MOVE with pos index as integer
